name: Load and Index

on:
  workflow_dispatch:
    inputs:
      searchIndex:
        description: "Search Index"
        required: true
        type: text

env:
  PYTHON_VERSION: "3.10"
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT}}
  AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER}}
  AZURE_SEARCH_SERVICE: ${{ secrets.AZURE_SEARCH_SERVICE}}
  AZURE_OPENAI_SERVICE: ${{ secrets.AZURE_OPENAI_SERVICE}}
  AZURE_OPENAI_EMB_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_EMB_DEPLOYMENT}}
  AZURE_SEARCH_INDEX: ${{ github.event.inputs.searchIndex }}
  AZURE_FORMRECOGNIZER_SERVICE: ${{ secrets.AZURE_FORMRECOGNIZER_SERVICE}}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID}}

jobs:
  load_and_index:
    name: "Load data and create Search Index"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - name: Install azd
        uses: Azure/setup-azd@v0.1.0
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run Prep Docs
        run: |
          echo 'Creating python virtual environment "scripts/.venv"'
          python3 -m venv scripts/.venv

          echo 'Installing dependencies from "requirements.txt" into virtual environment'
          ./scripts/.venv/bin/python -m pip install -r scripts/requirements.txt

          echo 'Running "prepdocs.py"'
          ./scripts/.venv/bin/python ./scripts/prepdocs.py './data/*' --storageaccount "$AZURE_STORAGE_ACCOUNT" --container "$AZURE_STORAGE_CONTAINER" --searchservice "$AZURE_SEARCH_SERVICE" --openaiservice "$AZURE_OPENAI_SERVICE" --openaideployment "$AZURE_OPENAI_EMB_DEPLOYMENT" --index "$AZURE_SEARCH_INDEX" --formrecognizerservice "$AZURE_FORMRECOGNIZER_SERVICE" --tenantid "$AZURE_TENANT_ID" -v
